name: Lumen C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: 安装依赖 (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev libncurses-dev patchelf

    - name: 安装依赖 (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install readline ncurses
    
    - name: 设置 CMake 缓存
      uses: actions/cache@v3
      with:
        path: |
          ~/.cmake
          ${{github.workspace}}/build
        key: ${{ runner.os }}-cmake-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-${{ matrix.build_type }}-
    
    - name: 配置和构建 (非Windows)
      if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install"
        cmake --build build --config ${{matrix.build_type}}
        cmake --install build --config ${{matrix.build_type}}

    - name: 配置和构建 (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install"
        cmake --build build --config ${{matrix.build_type}}
        cmake --install build --config ${{matrix.build_type}}

    - name: 测试
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure 